remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
title: Or Hadas
description: Atmospheric dynamics, storms, jets, and climate
url: https://orhadasatmosphere.github.io   # change USERNAME
baseurl: ""                       # keep empty unless this is a project site

author:
  name: Or Hadas
  avatar: /assets/img/20176F053.jpg
  bio: Atmospheric scientist studying storms, jets, and climate

links:
  - label: "Google Scholar"
    icon: "fas fa-graduation-cap"
    url: "https://scholar.google.co.il/citations?user=gYHd_jcAAAAJ"

  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/or-hadas-214048193/"

header_pages:
  - index.md
  - publications.md
